// src/renderer/src/components/AIAssistant.vue
<template>
  <div class="ai-assistant">
    <!-- Header -->
    <div class="header">
      <div class="title">
        <h1>🕊️ PelicanOS AI Assistant</h1>
        <div class="status-indicators">
          <div class="status-item" :class="{ active: ollamaStatus.connected }">
            <div class="status-dot"></div>
            <span>Ollama {{ ollamaStatus.connected ? 'Connected' : 'Disconnected' }}</span>
          </div>
          <div class="status-item" :class="{ active: chromaStatus.connected }">
            <div class="status-dot"></div>
            <span>Chroma {{ chromaStatus.connected ? 'Connected' : 'Disconnected' }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Service Management Panel -->
    <div class="service-panel" v-if="!allServicesConnected">
      <div class="service-controls">
        <h3>Service Management</h3>
        
        <div class="service-group">
          <div class="service-header">
            <h4>🦙 Ollama Service</h4>
            <button @click="checkOllamaStatus" class="btn-check">Check Status</button>
          </div>
          <div class="service-info">
            <p>Status: {{ ollamaStatus.message }}</p>
            <div v-if="!ollamaStatus.connected" class="service-actions">
              <button @click="startOllama" class="btn-start" :disabled="ollamaStatus.starting">
                {{ ollamaStatus.starting ? 'Starting...' : 'Start Ollama' }}
              </button>
              <p class="service-hint">Make sure Ollama is installed and available in PATH</p>
            </div>
            <div v-if="ollamaStatus.connected && availableModels.length === 0" class="model-actions">
              <button @click="pullDefaultModel" class="btn-pull" :disabled="pullingModel">
                {{ pullingModel ? 'Pulling Model...' : 'Pull Default Model (llama2)' }}
              </button>
            </div>
          </div>
        </div>

        <div class="service-group">
          <div class="service-header">
            <h4>🧬 ChromaDB Service</h4>
            <button @click="checkChromaStatus" class="btn-check">Check Status</button>
          </div>
          <div class="service-info">
            <p>Status: {{ chromaStatus.message }}</p>
            <div v-if="!chromaStatus.connected" class="service-actions">
              <button @click="startChroma" class="btn-start" :disabled="chromaStatus.starting">
                {{ chromaStatus.starting ? 'Starting...' : 'Start ChromaDB' }}
              </button>
              <p class="service-hint">ChromaDB will start on port 8000</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Main Chat Interface -->
    <div class="chat-container" v-if="allServicesConnected">
      <div class="model-selector">
        <label>AI Model:</label>
        <select v-model="selectedModel" @change="switchModel">
          <option v-for="model in availableModels" :key="model" :value="model">
            {{ model }}
          </option>
        </select>
        <button @click="refreshModels" class="btn-refresh">Refresh</button>
      </div>

      <div class="chat-messages" ref="messagesContainer">
        <div
          v-for="(message, index) in messages"
          :key="index"
          :class="['message', message.type]"
        >
          <div class="message-content">
            <div class="message-header">
              <span class="sender">{{ message.type === 'user' ? 'You' : 'AI' }}</span>
              <span class="timestamp">{{ formatTime(message.timestamp) }}</span>
            </div>
            <div class="message-text" v-html="formatMessage(message.content)"></div>
          </div>
        </div>
        
        <div v-if="isThinking" class="message ai thinking">
          <div class="message-content">
            <div class="message-header">
              <span class="sender">AI</span>
            </div>
            <div class="thinking-indicator">
              <span class="thinking-dots">Thinking</span>
            </div>
          </div>
        </div>
      </div>

      <div class="chat-input">
        <div class="input-container">
          <textarea
            v-model="currentMessage"
            @keydown="handleKeyDown"
            placeholder="Ask me anything..."
            class="message-input"
            rows="1"
            ref="messageInput"
          ></textarea>
          <button
            @click="sendMessage"
            :disabled="!currentMessage.trim() || isThinking"
            class="send-button"
          >
            <span v-if="!isThinking">Send</span>
            <span v-else>...</span>
          </button>
        </div>
        
        <div class="input-actions">
          <button @click="clearChat" class="btn-clear">Clear Chat</button>
          <button @click="exportChat" class="btn-export">Export</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, computed, nextTick } from 'vue'

// State management
const messages = ref<Array<{
  type: 'user' | 'ai'
  content: string
  timestamp: Date
}>>([])

const currentMessage = ref('')
const isThinking = ref(false)
const selectedModel = ref('llama2')
const availableModels = ref<string[]>([])
const pullingModel = ref(false)

const ollamaStatus = reactive({
  connected: false,
  message: 'Checking connection...',
  starting: false
})

const chromaStatus = reactive({
  connected: false,
  message: 'Checking connection...',
  starting: false
})

const messagesContainer = ref<HTMLElement>()
const messageInput = ref<HTMLTextAreaElement>()

// Computed properties
const allServicesConnected = computed(() => 
  ollamaStatus.connected && chromaStatus.connected
)

// Service management functions
async function checkOllamaStatus() {
  try {
    const response = await window.api.checkOllamaStatus()
    ollamaStatus.connected = response.connected
    ollamaStatus.message = response.message
    
    if (response.connected && response.models) {
      availableModels.value = response.models
    }
  } catch (error) {
    ollamaStatus.connected = false
    ollamaStatus.message = 'Failed to connect to Ollama'
  }
}

async function startOllama() {
  ollamaStatus.starting = true
  try {
    const response = await window.api.startOllama()
    ollamaStatus.connected = response.success
    ollamaStatus.message = response.message
    
    if (response.success) {
      await checkOllamaStatus()
    }
  } catch (error) {
    ollamaStatus.message = 'Failed to start Ollama'
  }
  ollamaStatus.starting = false
}

async function checkChromaStatus() {
  try {
    const response = await window.api.checkChromaStatus()
    chromaStatus.connected = response.connected
    chromaStatus.message = response.message
  } catch (error) {
    chromaStatus.connected = false
    chromaStatus.message = 'Failed to connect to ChromaDB'
  }
}

async function startChroma() {
  chromaStatus.starting = true
  try {
    const response = await window.api.startChroma()
    chromaStatus.connected = response.success
    chromaStatus.message = response.message
  } catch (error) {
    chromaStatus.message = 'Failed to start ChromaDB'
  }
  chromaStatus.starting = false
}
async function pullDefaultModel() {
  pullingModel.value = true
  try {
    const response = await window.api.pullModel('llama2')
    if (response.success) {
      await refreshModels()
    }
  } catch (error) {
    console.error('Failed to pull model:', error)
  }
  pullingModel.value = false
}

async function refreshModels() {
  try {
    const response = await window.api.getOllamaModels()
    if (response.success) {
      availableModels.value = response.models
    }
  } catch (error) {
    console.error('Failed to refresh models:', error)
  }
}

// Chat functions
async function sendMessage() {
  if (!currentMessage.value.trim() || isThinking.value) return
  
  const userMessage = currentMessage.value.trim()
  
  // Add user message
  messages.value.push({
    type: 'user',
    content: userMessage,
    timestamp: new Date()
  })
  
  currentMessage.value = ''
  isThinking.value = true
  
  // Auto-resize textarea
  nextTick(() => {
    if (messageInput.value) {
      messageInput.value.style.height = 'auto'
    }
  })
  
  try {
    // Send to AI
    const response = await window.api.chatWithAI({
      message: userMessage,
      model: selectedModel.value,
      history: messages.value.slice(-10) // Send last 10 messages for context
    })
    
    if (response.success) {
      messages.value.push({
        type: 'ai',
        content: response.message,
        timestamp: new Date()
      })
    } else {
      messages.value.push({
        type: 'ai',
        content: 'Sorry, I encountered an error processing your request.',
        timestamp: new Date()
      })
    }
  } catch (error) {
    messages.value.push({
      type: 'ai',
      content: 'Sorry, I encountered an error processing your request.',
      timestamp: new Date()
    })
  }
  
  isThinking.value = false
  scrollToBottom()
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    sendMessage()
  }
}

function switchModel() {
  // Model switching logic if needed
  console.log('Switched to model:', selectedModel.value)
}

function clearChat() {
  messages.value = []
}

function exportChat() {
  const chatData = {
    timestamp: new Date().toISOString(),
    messages: messages.value
  }
  
  const dataStr = JSON.stringify(chatData, null, 2)
  const dataBlob = new Blob([dataStr], { type: 'application/json' })
  const url = URL.createObjectURL(dataBlob)
  
  const link = document.createElement('a')
  link.href = url
  link.download = `chat-export-${new Date().toISOString().split('T')[0]}.json`
  link.click()
  
  URL.revokeObjectURL(url)
}

// Utility functions
function formatTime(date: Date): string {
  return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

function formatMessage(content: string): string {
  // Basic markdown-like formatting
  return content
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code>$1</code>')
    .replace(/\n/g, '<br>')
}

function scrollToBottom() {
  nextTick(() => {
    if (messagesContainer.value) {
      messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight
    }
  })
}

// Lifecycle
onMounted(async () => {
  await checkOllamaStatus()
  await checkChromaStatus()
  
  // Add welcome message
  messages.value.push({
    type: 'ai',
    content: 'Hello! I\'m your PelicanOS AI Assistant. I\'m powered by Ollama and ChromaDB for local AI processing. How can I help you today?',
    timestamp: new Date()
  })
  
  scrollToBottom()
})
</script>

<style scoped>
.ai-assistant {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.header {
  padding: 1rem 2rem;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.title h1 {
  margin: 0;
  font-size: 1.8rem;
  font-weight: 600;
}

.status-indicators {
  display: flex;
  gap: 1rem;
  margin-top: 0.5rem;
}

.status-item {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.9rem;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #ff6b6b;
  transition: background-color 0.3s;
}

.status-item.active .status-dot {
  background: #51cf66;
}

.service-panel {
  flex: 1;
  padding: 2rem;
  overflow-y: auto;
}

.service-controls {
  max-width: 800px;
  margin: 0 auto;
}

.service-controls h3 {
  margin-bottom: 2rem;
  text-align: center;
  font-size: 1.5rem;
}

.service-group {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 12px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
  backdrop-filter: blur(10px);
}

.service-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.service-header h4 {
  margin: 0;
  font-size: 1.2rem;
}

.service-info p {
  margin: 0.5rem 0;
  opacity: 0.9;
}

.service-actions, .model-actions {
  margin-top: 1rem;
}

.service-hint {
  font-size: 0.8rem;
  opacity: 0.7;
  margin-top: 0.5rem;
}

.chat-container {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-height: 0;
}

.model-selector {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 1rem 2rem;
  background: rgba(0, 0, 0, 0.1);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.model-selector select {
  padding: 0.5rem;
  border-radius: 6px;
  border: none;
  background: rgba(255, 255, 255, 0.9);
  color: #333;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 1rem 2rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.message {
  display: flex;
  max-width: 80%;
}

.message.user {
  align-self: flex-end;
}

.message.ai {
  align-self: flex-start;
}

.message-content {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 12px;
  padding: 1rem;
  backdrop-filter: blur(10px);
}

.message.user .message-content {
  background: rgba(255, 255, 255, 0.2);
}

.message-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
  font-size: 0.8rem;
  opacity: 0.8;
}

.message-text {
  line-height: 1.5;
}

.thinking-indicator {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.thinking-dots::after {
  content: '...';
  animation: thinking 1.5s infinite;
}

@keyframes thinking {
  0%, 20% { content: '.'; }
  40% { content: '..'; }
  60%, 100% { content: '...'; }
}

.chat-input {
  padding: 1rem 2rem;
  background: rgba(0, 0, 0, 0.2);
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.input-container {
  display: flex;
  gap: 1rem;
  margin-bottom: 1rem;
}

.message-input {
  flex: 1;
  padding: 1rem;
  border-radius: 12px;
  border: none;
  background: rgba(255, 255, 255, 0.9);
  color: #333;
  resize: none;
  min-height: 50px;
  max-height: 150px;
}

.send-button {
  padding: 1rem 2rem;
  border-radius: 12px;
  border: none;
  background: #51cf66;
  color: white;
  cursor: pointer;
  font-weight: 600;
  transition: all 0.3s;
}

.send-button:hover:not(:disabled) {
  background: #40c057;
  transform: translateY(-2px);
}

.send-button:disabled {
  background: #868e96;
  cursor: not-allowed;
}

.input-actions {
  display: flex;
  gap: 1rem;
  justify-content: center;
}

/* Button styles */
.btn-check, .btn-start, .btn-pull, .btn-refresh, .btn-clear, .btn-export {
  padding: 0.5rem 1rem;
  border-radius: 8px;
  border: none;
  background: rgba(255, 255, 255, 0.2);
  color: white;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.3s;
}

.btn-check:hover, .btn-refresh:hover, .btn-clear:hover, .btn-export:hover {
  background: rgba(255, 255, 255, 0.3);
  transform: translateY(-1px);
}

.btn-start, .btn-pull {
  background: #51cf66;
}

.btn-start:hover:not(:disabled), .btn-pull:hover:not(:disabled) {
  background: #40c057;
  transform: translateY(-1px);
}

.btn-start:disabled, .btn-pull:disabled {
  background: #868e96;
  cursor: not-allowed;
}

/* Scrollbar styling */
.chat-messages::-webkit-scrollbar {
  width: 8px;
}

.chat-messages::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.1);
  border-radius: 4px;
}

.chat-messages::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.3);
  border-radius: 4px;
}

.chat-messages::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.5);
}
</style>

// src/renderer/src/components/AIAssistant.tsx
import React, { useState, useEffect } from 'react'
import { Button } from './ui/button'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import { Textarea } from './ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select'
import { CheckCircle, Circle, Send, RefreshCw, Trash2, Download, Bot, User, Brain, Settings } from 'lucide-react'
import AdvancedMemoryPanel from './AdvancedMemoryPanel'
import MemoryHealthIndicator from './MemoryHealthIndicator'
import type { MemoryStore } from '../types/chat'

interface Message {
  type: 'user' | 'ai'
  content: string
  timestamp: Date
}

interface ServiceStatus {
  connected: boolean
  message: string
  starting: boolean
}

const AIAssistant: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([])
  const [currentMessage, setCurrentMessage] = useState('')
  const [isThinking, setIsThinking] = useState(false)
  const [selectedModel, setSelectedModel] = useState('tinydolphin:latest')
  const [availableModels, setAvailableModels] = useState<string[]>([])
  const [showMemoryPanel, setShowMemoryPanel] = useState(false)
  const [memoryStore, setMemoryStore] = useState<MemoryStore | null>(null)

  const [ollamaStatus, setOllamaStatus] = useState<ServiceStatus>({
    connected: false,
    message: 'Checking connection...',
    starting: false
  })

  const [chromaStatus, setChromaStatus] = useState<ServiceStatus>({
    connected: false,
    message: 'Checking connection...',
    starting: false
  })

  const allServicesConnected = ollamaStatus.connected && chromaStatus.connected

  const checkOllamaStatus = async () => {
    try {
      const response = await window.api.checkOllamaStatus()
      setOllamaStatus({
        connected: response.connected,
        message: response.message,
        starting: false
      })
      
      if (response.connected && response.models) {
        setAvailableModels(response.models)
        if (response.models.length > 0 && !response.models.includes(selectedModel)) {
          setSelectedModel(response.models[0])
        }
      }
    } catch (error) {
      setOllamaStatus({
        connected: false,
        message: 'Failed to connect to Ollama',
        starting: false
      })
    }
  }

  const startOllama = async () => {
    setOllamaStatus(prev => ({ ...prev, starting: true }))
    try {
      const response = await window.api.startOllama()
      setOllamaStatus({
        connected: response.success,
        message: response.message,
        starting: false
      })
      
      if (response.success) {
        await checkOllamaStatus()
      }
    } catch (error) {
      setOllamaStatus({
        connected: false,
        message: 'Failed to start Ollama',
        starting: false
      })
    }
  }

  const checkChromaStatus = async () => {
    try {
      const response = await window.api.checkChromaStatus()
      setChromaStatus({
        connected: response.connected,
        message: response.message,
        starting: false
      })
    } catch (error) {
      setChromaStatus({
        connected: false,
        message: 'Failed to connect to ChromaDB',
        starting: false
      })
    }
  }

  const startChroma = async () => {
    setChromaStatus(prev => ({ ...prev, starting: true }))
    try {
      const response = await window.api.startChroma()
      setChromaStatus({
        connected: response.success,
        message: response.message,
        starting: false
      })
    } catch (error) {
      setChromaStatus({
        connected: false,
        message: 'Failed to start ChromaDB',
        starting: false
      })
    }
  }

  const sendMessage = async () => {
    if (!currentMessage.trim() || isThinking) return
    
    const userMessage = currentMessage.trim()
    const newMessage: Message = {
      type: 'user',
      content: userMessage,
      timestamp: new Date()
    }
    setMessages(prev => [...prev, newMessage])
    setCurrentMessage('')
    setIsThinking(true)
    
    try {
      const response = await window.api.chatWithAI({
        message: userMessage,
        model: selectedModel,
        history: messages.slice(-10)
      })
      
      const aiMessage: Message = {
        type: 'ai',
        content: response.success ? response.message : 'Sorry, I encountered an error.',
        timestamp: new Date()
      }
      setMessages(prev => [...prev, aiMessage])
    } catch (error) {
      const errorMessage: Message = {
        type: 'ai',
        content: 'Sorry, I encountered an error.',
        timestamp: new Date()
      }
      setMessages(prev => [...prev, errorMessage])
    }
    
    setIsThinking(false)
  }

  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault()
      sendMessage()
    }
  }

  const formatTime = (date: Date): string => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  }

  const clearChat = () => setMessages([])

  const loadMemoryStore = async () => {
    try {
      const store = await window.api.getMemoryStore()
      setMemoryStore(store)
    } catch (error) {
      console.error('Failed to load memory store:', error)
      setMemoryStore(null)
    }
  }

  const exportChat = () => {
    const chatData = {
      timestamp: new Date().toISOString(),
      messages: messages
    }
    
    const dataStr = JSON.stringify(chatData, null, 2)
    const dataBlob = new Blob([dataStr], { type: 'application/json' })
    const url = URL.createObjectURL(dataBlob)
    
    const link = document.createElement('a')
    link.href = url
    link.download = `chat-export-${new Date().toISOString().split('T')[0]}.json`
    link.click()
    
    URL.revokeObjectURL(url)
  }

  useEffect(() => {
    const initializeServices = async () => {
      await checkOllamaStatus()
      await checkChromaStatus()
      await loadMemoryStore()
      
      const welcomeMessage: Message = {
        type: 'ai',
        content: 'Hello! I\'m your PelicanOS AI Assistant. How can I help you today?',
        timestamp: new Date()
      }
      setMessages([welcomeMessage])
    }
    
    initializeServices()
  }, [])

  return (
    <div className="flex flex-col h-screen bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500">
      {/* Header */}
      <div className="flex items-center justify-between p-4 bg-black/20 backdrop-blur-sm border-b border-white/10">
        <div>
          <h1 className="text-2xl font-bold text-white">🕊️ PelicanOS AI Assistant</h1>
          <div className="flex gap-4 mt-2">
            <div className="flex items-center gap-2">
              {ollamaStatus.connected ? (
                <CheckCircle className="w-4 h-4 text-green-400" />
              ) : (
                <Circle className="w-4 h-4 text-red-400" />
              )}
              <span className="text-sm text-white/80">
                Ollama {ollamaStatus.connected ? 'Connected' : 'Disconnected'}
              </span>
            </div>
            <div className="flex items-center gap-2">
              {chromaStatus.connected ? (
                <CheckCircle className="w-4 h-4 text-green-400" />
              ) : (
                <Circle className="w-4 h-4 text-red-400" />
              )}
              <span className="text-sm text-white/80">
                ChromaDB {chromaStatus.connected ? 'Connected' : 'Disconnected'}
              </span>
            </div>
          </div>
        </div>
        
        {/* Memory Health Indicator */}
        <div className="group relative">
          <MemoryHealthIndicator 
            memoryStore={memoryStore} 
            className="text-white/80"
          />
        </div>
      </div>

      {/* Service Setup Panel */}
      {!allServicesConnected && (
        <div className="flex-1 p-6 overflow-auto">
          <div className="max-w-4xl mx-auto">
            <Card className="bg-white/10 backdrop-blur-sm border-white/20">
              <CardHeader>
                <CardTitle className="text-white">Service Management</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-white">🦙 Ollama Service</h3>
                    <Button variant="outline" size="sm" onClick={checkOllamaStatus}>
                      Check Status
                    </Button>
                  </div>
                  <p className="text-white/80">{ollamaStatus.message}</p>
                  {!ollamaStatus.connected && (
                    <Button 
                      onClick={startOllama} 
                      disabled={ollamaStatus.starting}
                      className="bg-green-600 hover:bg-green-700"
                    >
                      {ollamaStatus.starting ? 'Starting...' : 'Start Ollama'}
                    </Button>
                  )}
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-white">🧬 ChromaDB Service</h3>
                    <Button variant="outline" size="sm" onClick={checkChromaStatus}>
                      Check Status
                    </Button>
                  </div>
                  <p className="text-white/80">{chromaStatus.message}</p>
                  {!chromaStatus.connected && (
                    <Button 
                      onClick={startChroma} 
                      disabled={chromaStatus.starting}
                      className="bg-orange-600 hover:bg-orange-700"
                    >
                      {chromaStatus.starting ? 'Starting...' : 'Start ChromaDB'}
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      )}

      {/* Chat Interface */}
      {allServicesConnected && (
        <div className="flex flex-col flex-1 min-h-0">
          {/* Model Selector */}
          <div className="flex items-center gap-4 p-4 bg-black/10 backdrop-blur-sm">
            <label className="text-white font-medium">AI Model:</label>
            <Select value={selectedModel} onValueChange={setSelectedModel}>
              <SelectTrigger className="w-64">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {availableModels.map(model => (
                  <SelectItem key={model} value={model}>
                    {model}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button variant="outline" size="sm" onClick={() => setShowMemoryPanel(true)}>
              <Brain className="w-4 h-4 mr-2" />
              Memory
            </Button>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-auto p-4">
            <div className="space-y-4 max-w-4xl mx-auto">
              {messages.map((message, index) => (
                <div key={index} className={`flex gap-3 ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <Card className="max-w-[80%] bg-white/10 backdrop-blur-sm border-white/20">
                    <CardContent className="p-3">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-white">
                          {message.type === 'user' ? 'You' : 'AI'}
                        </span>
                        <span className="text-xs text-white/60">
                          {formatTime(message.timestamp)}
                        </span>
                      </div>
                      <p className="text-white">{message.content}</p>
                    </CardContent>
                  </Card>
                </div>
              ))}

              {isThinking && (
                <div className="flex gap-3 justify-start">
                  <Card className="max-w-[80%] bg-white/10 backdrop-blur-sm border-white/20">
                    <CardContent className="p-3">
                      <div className="flex items-center gap-2">
                        <div className="flex space-x-1">
                          <div className="w-2 h-2 bg-white rounded-full animate-bounce"></div>
                          <div className="w-2 h-2 bg-white rounded-full animate-bounce [animation-delay:0.1s]"></div>
                          <div className="w-2 h-2 bg-white rounded-full animate-bounce [animation-delay:0.2s]"></div>
                        </div>
                        <span className="text-white/80">Thinking...</span>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              )}
            </div>
          </div>

          {/* Input Area */}
          <div className="p-4 bg-black/10 backdrop-blur-sm">
            <div className="max-w-4xl mx-auto space-y-3">
              <div className="flex gap-3">
                <Textarea
                  value={currentMessage}
                  onChange={(e) => setCurrentMessage(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Ask me anything..."
                  className="flex-1 bg-white/10 border-white/20 text-white placeholder:text-white/50"
                  disabled={isThinking}
                />
                <Button
                  onClick={sendMessage}
                  disabled={!currentMessage.trim() || isThinking}
                  className="bg-green-600 hover:bg-green-700"
                >
                  <Send className="w-4 h-4" />
                </Button>
              </div>
              
              <div className="flex justify-center gap-3">
                <Button variant="outline" size="sm" onClick={clearChat}>
                  <Trash2 className="w-4 h-4 mr-2" />
                  Clear
                </Button>
                <Button variant="outline" size="sm" onClick={exportChat}>
                  <Download className="w-4 h-4 mr-2" />
                  Export
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
      
      {/* Advanced Memory Panel */}
      <AdvancedMemoryPanel 
        isOpen={showMemoryPanel} 
        onClose={() => {
          setShowMemoryPanel(false)
          loadMemoryStore() // Refresh memory store when panel closes
        }} 
      />
    </div>
  )
}

export default AIAssistant
