// src/renderer/src/components/DeveloperPanel.tsx
import React, { useState, useEffect, useRef } from 'react'
import { Button } from './ui/button'
import { Textarea } from './ui/textarea'
import { Input } from './ui/input'
import { 
  Terminal, 
  FloppyDisk, 
  Folder, 
  File, 
  Plus, 
  X, 
  Play, 
  FolderOpen,
  Trash,
  Copy,
  ArrowClockwise
} from 'phosphor-react'

// Declare the window.api type
declare global {
  interface Window {
    api: {
      fsReadFile: (filePath: string) => Promise<{ success: boolean; content?: string; error?: string }>
      fsWriteFile: (filePath: string, content: string) => Promise<{ success: boolean; error?: string }>
      fsListDirectory: (dirPath: string) => Promise<{ success: boolean; files?: any[]; error?: string }>
      fsCreateFile: (filePath: string, content?: string) => Promise<{ success: boolean; error?: string }>
      fsDeleteFile: (filePath: string) => Promise<{ success: boolean; error?: string }>
      fsExecuteCommand: (command: string, cwd?: string) => Promise<{ success: boolean; stdout?: string; stderr?: string; error?: string }>
      fsOpenFileDialog: () => Promise<{ success: boolean; filePath?: string; error?: string }>
      fsSaveFileDialog: (defaultName?: string, content?: string) => Promise<{ success: boolean; filePath?: string; error?: string }>
      fsGetFileInfo: (filePath: string) => Promise<{ success: boolean; info?: any; error?: string }>
    }
  }
}

interface FileTab {
  id: string
  name: string
  path: string
  content: string
  isModified: boolean
  language: string
}

interface FileItem {
  name: string
  isDirectory: boolean
  isFile: boolean
  path: string
}

interface TerminalOutput {
  id: string
  command: string
  output: string
  error?: string
  timestamp: Date
}

const DeveloperPanel: React.FC = () => {
  const [activeTab, setActiveTab] = useState<string | null>(null)
  const [tabs, setTabs] = useState<FileTab[]>([])
  const [currentDirectory, setCurrentDirectory] = useState<string>('')
  const [directoryContents, setDirectoryContents] = useState<FileItem[]>([])
  const [terminalHistory, setTerminalHistory] = useState<TerminalOutput[]>([])
  const [currentCommand, setCurrentCommand] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const terminalRef = useRef<HTMLDivElement>(null)

  // Initialize with home directory
  useEffect(() => {
    const initHomeDirectory = async () => {
      try {
        // Try to get user's home directory by executing pwd or echo %USERPROFILE%
        const result = await window.api.fsExecuteCommand(process.platform === 'win32' ? 'echo %USERPROFILE%' : 'echo $HOME')
        if (result.success && result.stdout) {
          const homeDir = result.stdout.trim()
          setCurrentDirectory(homeDir)
          await loadDirectory(homeDir)
        } else {
          // Fallback to a default directory
          const fallbackDir = process.platform === 'win32' ? 'C:\\' : '/'
          setCurrentDirectory(fallbackDir)
          await loadDirectory(fallbackDir)
        }
      } catch (error) {
        console.error('Error initializing directory:', error)
        // Set a safe fallback
        const fallbackDir = process.platform === 'win32' ? 'C:\\' : '/'
        setCurrentDirectory(fallbackDir)
        await loadDirectory(fallbackDir)
      }
    }

    initHomeDirectory()
  }, [])

  // Auto-scroll terminal
  useEffect(() => {
    if (terminalRef.current) {
      terminalRef.current.scrollTop = terminalRef.current.scrollHeight
    }
  }, [terminalHistory])

  const loadDirectory = async (dirPath: string) => {
    setIsLoading(true)
    try {
      const result = await window.api.fsListDirectory(dirPath)
      if (result.success && result.files) {
        setDirectoryContents(result.files)
        setCurrentDirectory(dirPath)
      } else {
        console.error('Failed to load directory:', result.error)
        addTerminalOutput(`Error loading directory: ${result.error}`, true)
      }
    } catch (error) {
      console.error('Error loading directory:', error)
      addTerminalOutput(`Error loading directory: ${error}`, true)
    } finally {
      setIsLoading(false)
    }
  }

  const openFile = async (filePath: string) => {
    try {
      const result = await window.api.fsReadFile(filePath)
      if (result.success && result.content !== undefined) {
        const fileName = filePath.split(/[\\/]/).pop() || 'unknown'
        const fileExtension = fileName.split('.').pop()?.toLowerCase() || ''
        
        // Check if file is already open
        const existingTab = tabs.find(tab => tab.path === filePath)
        if (existingTab) {
          setActiveTab(existingTab.id)
          return
        }

        const newTab: FileTab = {
          id: `tab-${Date.now()}`,
          name: fileName,
          path: filePath,
          content: result.content,
          isModified: false,
          language: getLanguageFromExtension(fileExtension)
        }

        setTabs(prev => [...prev, newTab])
        setActiveTab(newTab.id)
        addTerminalOutput(`Opened file: ${filePath}`)
      } else {
        console.error('Failed to read file:', result.error)
        addTerminalOutput(`Error reading file: ${result.error}`, true)
      }
    } catch (error) {
      console.error('Error opening file:', error)
      addTerminalOutput(`Error opening file: ${error}`, true)
    }
  }

  const saveFile = async (tabId: string) => {
    const tab = tabs.find(t => t.id === tabId)
    if (!tab) return

    try {
      const result = await window.api.fsWriteFile(tab.path, tab.content)
      if (result.success) {
        setTabs(prev => prev.map(t => 
          t.id === tabId ? { ...t, isModified: false } : t
        ))
        addTerminalOutput(`Saved file: ${tab.path}`)
      } else {
        console.error('Failed to save file:', result.error)
        addTerminalOutput(`Error saving file: ${result.error}`, true)
      }
    } catch (error) {
      console.error('Error saving file:', error)
      addTerminalOutput(`Error saving file: ${error}`, true)
    }
  }

  const createNewFile = async () => {
    try {
      const result = await window.api.fsSaveFileDialog('untitled.txt', '')
      if (result.success && result.filePath) {
        await openFile(result.filePath)
        addTerminalOutput(`Created new file: ${result.filePath}`)
        // Refresh directory if the new file is in current directory
        if (result.filePath.includes(currentDirectory)) {
          await loadDirectory(currentDirectory)
        }
      }
    } catch (error) {
      console.error('Error creating file:', error)
      addTerminalOutput(`Error creating file: ${error}`, true)
    }
  }

  const openFileDialog = async () => {
    try {
      const result = await window.api.fsOpenFileDialog()
      if (result.success && result.filePath) {
        await openFile(result.filePath)
      }
    } catch (error) {
      console.error('Error opening file dialog:', error)
      addTerminalOutput(`Error opening file dialog: ${error}`, true)
    }
  }

  const closeTab = (tabId: string) => {
    setTabs(prev => prev.filter(t => t.id !== tabId))
    if (activeTab === tabId) {
      const remainingTabs = tabs.filter(t => t.id !== tabId)
      setActiveTab(remainingTabs.length > 0 ? remainingTabs[remainingTabs.length - 1].id : null)
    }
  }

  const updateTabContent = (tabId: string, content: string) => {
    setTabs(prev => prev.map(t => 
      t.id === tabId ? { ...t, content, isModified: true } : t
    ))
  }

  const executeCommand = async () => {
    if (!currentCommand.trim()) return

    const command = currentCommand.trim()
    setCurrentCommand('')
    
    addTerminalOutput(`$ ${command}`)

    try {
      const result = await window.api.fsExecuteCommand(command, currentDirectory)
      
      if (result.success) {
        if (result.stdout) addTerminalOutput(result.stdout)
        if (result.stderr) addTerminalOutput(result.stderr, true)
        
        // Check if command might have changed directory
        if (command.startsWith('cd ')) {
          // Refresh current directory listing
          await loadDirectory(currentDirectory)
        }
      } else {
        addTerminalOutput(result.error || 'Command failed', true)
      }
    } catch (error) {
      addTerminalOutput(`Error executing command: ${error}`, true)
    }
  }

  const addTerminalOutput = (output: string, isError: boolean = false) => {
    const newOutput: TerminalOutput = {
      id: `output-${Date.now()}-${Math.random()}`,
      command: isError ? 'ERROR' : 'INFO',
      output,
      error: isError ? output : undefined,
      timestamp: new Date()
    }
    setTerminalHistory(prev => [...prev, newOutput])
  }

  const clearTerminal = () => {
    setTerminalHistory([])
  }

  const navigateToParentDirectory = async () => {
    const parentDir = currentDirectory.split(/[\\/]/).slice(0, -1).join(process.platform === 'win32' ? '\\' : '/')
    if (parentDir && parentDir !== currentDirectory) {
      await loadDirectory(parentDir || (process.platform === 'win32' ? 'C:\\' : '/'))
    }
  }

  const getLanguageFromExtension = (extension: string): string => {
    const languageMap: { [key: string]: string } = {
      'js': 'javascript',
      'jsx': 'javascript',
      'ts': 'typescript',
      'tsx': 'typescript',
      'py': 'python',
      'html': 'html',
      'css': 'css',
      'json': 'json',
      'md': 'markdown',
      'txt': 'text',
      'yaml': 'yaml',
      'yml': 'yaml',
      'xml': 'xml',
      'sh': 'bash',
      'bat': 'batch'
    }
    return languageMap[extension] || 'text'
  }

  const currentTab = activeTab ? tabs.find(t => t.id === activeTab) : null

  return (
    <div className="w-2/5 bg-gray-900 text-white flex flex-col h-full">
      {/* Developer Panel Header */}
      <div className="bg-gray-800 border-b border-gray-700 p-3">
        <div className="flex items-center justify-between">
          <h3 className="font-semibold flex items-center gap-2">
            <Terminal size={18} />
            Developer Mode
          </h3>
          <div className="flex gap-2">
            <Button
              onClick={createNewFile}
              size="sm"
              className="bg-blue-600 hover:bg-blue-700 text-xs"
            >
              <Plus size={14} />
              New
            </Button>
            <Button
              onClick={openFileDialog}
              size="sm"
              className="bg-green-600 hover:bg-green-700 text-xs"
            >
              <FolderOpen size={14} />
              Open
            </Button>
          </div>
        </div>
      </div>

      {/* File Tabs */}
      {tabs.length > 0 && (
        <div className="bg-gray-800 border-b border-gray-700 flex overflow-x-auto">
          {tabs.map(tab => (
            <div
              key={tab.id}
              className={`flex items-center gap-2 px-3 py-2 cursor-pointer border-r border-gray-700 min-w-0 ${
                activeTab === tab.id ? 'bg-gray-700' : 'hover:bg-gray-750'
              }`}
              onClick={() => setActiveTab(tab.id)}
            >
              <File size={14} />
              <span className="truncate text-sm">
                {tab.name}
                {tab.isModified && '*'}
              </span>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  closeTab(tab.id)
                }}
                className="text-gray-400 hover:text-white"
              >
                <X size={12} />
              </button>
            </div>
          ))}
        </div>
      )}

      <div className="flex-1 flex">
        {/* File Explorer */}
        <div className="w-1/3 bg-gray-850 border-r border-gray-700 flex flex-col">
          <div className="p-3 border-b border-gray-700">
            <div className="flex items-center gap-2 mb-2">
              <Folder size={16} />
              <span className="text-sm font-medium">Explorer</span>
              <Button
                onClick={() => loadDirectory(currentDirectory)}
                size="sm"
                className="ml-auto bg-transparent hover:bg-gray-700 p-1"
              >
                <ArrowClockwise size={12} />
              </Button>
            </div>
            <div className="flex items-center gap-1">
              <Button
                onClick={navigateToParentDirectory}
                size="sm"
                className="bg-transparent hover:bg-gray-700 p-1"
                disabled={!currentDirectory || currentDirectory === '/' || !currentDirectory.match(/^[A-Za-z]:\\?$/)}
              >
                ↑
              </Button>
              <div className="text-xs text-gray-400 truncate flex-1">
                {currentDirectory}
              </div>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto p-2">
            {isLoading ? (
              <div className="text-gray-400 text-sm">Loading...</div>
            ) : (
              <div className="space-y-1">
                {directoryContents.map((item, index) => (
                  <div
                    key={index}
                    className="flex items-center gap-2 p-2 rounded hover:bg-gray-700 cursor-pointer text-sm"
                    onClick={() => {
                      if (item.isDirectory) {
                        loadDirectory(item.path)
                      } else {
                        openFile(item.path)
                      }
                    }}
                  >
                    {item.isDirectory ? (
                      <Folder size={14} className="text-blue-400" />
                    ) : (
                      <File size={14} className="text-gray-400" />
                    )}
                    <span className="truncate">{item.name}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Code Editor / Terminal */}
        <div className="flex-1 flex flex-col">
          {/* Code Editor */}
          {currentTab && (
            <div className="flex-1 flex flex-col">
              <div className="bg-gray-800 border-b border-gray-700 p-2 flex items-center justify-between">
                <span className="text-sm text-gray-300">{currentTab.name}</span>
                <Button
                  onClick={() => saveFile(currentTab.id)}
                  size="sm"
                  className="bg-blue-600 hover:bg-blue-700 text-xs"
                  disabled={!currentTab.isModified}
                >
                  <FloppyDisk size={14} />
                  Save
                </Button>
              </div>
              <Textarea
                value={currentTab.content}
                onChange={(e) => updateTabContent(currentTab.id, e.target.value)}
                className="flex-1 bg-gray-900 text-white font-mono text-sm border-none resize-none focus:ring-0 rounded-none"
                placeholder="Start coding..."
              />
            </div>
          )}

          {/* Terminal */}
          <div className="h-64 bg-black border-t border-gray-700 flex flex-col">
            <div className="bg-gray-800 border-b border-gray-700 p-2 flex items-center justify-between">
              <span className="text-sm text-gray-300 flex items-center gap-2">
                <Terminal size={14} />
                Terminal
              </span>
              <Button
                onClick={clearTerminal}
                size="sm"
                className="bg-red-600 hover:bg-red-700 text-xs"
              >
                <Trash size={12} />
                Clear
              </Button>
            </div>

            <div ref={terminalRef} className="flex-1 overflow-y-auto p-3 font-mono text-sm">
              {terminalHistory.map((output) => (
                <div key={output.id} className={`mb-1 ${output.error ? 'text-red-400' : 'text-green-400'}`}>
                  {output.output}
                </div>
              ))}
            </div>

            <div className="border-t border-gray-700 p-2">
              <div className="flex items-center gap-2">
                <span className="text-green-400">$</span>
                <Input
                  value={currentCommand}
                  onChange={(e) => setCurrentCommand(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && executeCommand()}
                  className="flex-1 bg-transparent border-none text-white font-mono text-sm focus:ring-0 p-0"
                  placeholder="Enter command..."
                />
                <Button
                  onClick={executeCommand}
                  size="sm"
                  className="bg-green-600 hover:bg-green-700"
                  disabled={!currentCommand.trim()}
                >
                  <Play size={14} />
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default DeveloperPanel

// src/renderer/src/components/DeveloperPanel.vue
<template>
  <div class="developer-panel">
    <!-- Header Bar -->
    <div class="panel-header">
      <div class="header-left">
        <div class="developer-badge">
          <span class="badge-icon">⚡</span>
          <span class="badge-text">Developer Mode</span>
        </div>
      </div>
      
      <div class="header-actions">
        <button @click="toggleTerminal" class="header-btn" :class="{ active: terminalVisible }">
          <span class="btn-icon">🖥️</span>
          <span class="btn-text">Terminal</span>
        </button>
        
        <button @click="shareProject" class="header-btn">
          <span class="btn-icon">📤</span>
          <span class="btn-text">Share</span>
        </button>
        
        <button @click="$emit('close')" class="header-btn close-btn">
          <span class="btn-icon">✕</span>
        </button>
      </div>
    </div>

    <!-- File Navigation -->
    <div class="file-nav">
      <div class="nav-tabs">
        <button 
          v-for="file in openFiles" 
          :key="file.id"
          @click="setActiveFile(file.id)"
          :class="['file-tab', { active: activeFileId === file.id }]"
        >
          <span class="file-icon">{{ getFileIcon(file.name) }}</span>
          <span class="file-name">{{ file.name }}</span>
          <button @click.stop="closeFile(file.id)" class="close-file">×</button>
        </button>
        
        <button @click="openNewFile" class="file-tab new-file">
          <span class="file-icon">+</span>
          <span class="file-name">New File</span>
        </button>
      </div>
      
      <div class="nav-actions">
        <button @click="saveCurrentFile" class="nav-btn" :disabled="!hasUnsavedChanges">
          <span class="btn-icon">💾</span>
        </button>
        <button @click="openFileDialog" class="nav-btn">
          <span class="btn-icon">📁</span>
        </button>
      </div>
    </div>

    <!-- Code Editor Area -->
    <div class="editor-container" :class="{ 'with-terminal': terminalVisible }">
      <div class="editor-wrapper">
        <div v-if="activeFile" class="code-editor">
          <div class="editor-header">
            <span class="file-path">{{ activeFile.path || activeFile.name }}</span>
            <span v-if="activeFile.modified" class="modified-indicator">●</span>
          </div>
          
          <textarea
            v-model="activeFile.content"
            @input="handleFileChange"
            class="code-textarea"
            :placeholder="getEditorPlaceholder()"
            spellcheck="false"
          ></textarea>
        </div>
        
        <div v-else class="editor-placeholder">
          <div class="placeholder-content">
            <div class="placeholder-icon">📝</div>
            <h3>No file selected</h3>
            <p>Open a file or create a new one to start coding</p>
            <button @click="openNewFile" class="create-file-btn">
              Create New File
            </button>
          </div>
        </div>
      </div>

      <!-- Terminal Drawer -->
      <div v-if="terminalVisible" class="terminal-drawer">
        <div class="terminal-header">
          <div class="terminal-title">
            <span class="terminal-icon">🖥️</span>
            <span>Terminal</span>
          </div>
          <div class="terminal-actions">
            <button @click="clearTerminal" class="terminal-btn">Clear</button>
            <button @click="toggleTerminal" class="terminal-btn">Hide</button>
          </div>
        </div>
        
        <div class="terminal-content" ref="terminalContent">
          <div 
            v-for="(line, index) in terminalHistory" 
            :key="index"
            class="terminal-line"
            :class="line.type"
          >
            <span v-if="line.type === 'command'" class="terminal-prompt">$</span>
            <span class="terminal-text">{{ line.text }}</span>
          </div>
        </div>
        
        <div class="terminal-input">
          <span class="terminal-prompt">$</span>
          <input
            v-model="currentCommand"
            @keydown="handleTerminalInput"
            class="command-input"
            placeholder="Type a command..."
            ref="terminalInput"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, nextTick } from 'vue'

// Props & Emits
const emit = defineEmits(['close'])

// Types
interface FileTab {
  id: string
  name: string
  content: string
  path?: string
  language?: string
  modified?: boolean
}

interface TerminalLine {
  type: 'command' | 'output' | 'error'
  text: string
  timestamp?: Date
}

// State
const openFiles = ref<FileTab[]>([])
const activeFileId = ref<string | null>(null)
const terminalVisible = ref(false)
const terminalHistory = ref<TerminalLine[]>([
  { type: 'output', text: 'PelicanOS Developer Terminal' },
  { type: 'output', text: 'Type "help" for available commands' }
])
const currentCommand = ref('')
const terminalContent = ref<HTMLElement>()
const terminalInput = ref<HTMLInputElement>()

// Computed
const activeFile = computed(() => {
  if (!activeFileId.value) return null
  return openFiles.value.find(f => f.id === activeFileId.value) || null
})

const hasUnsavedChanges = computed(() => {
  return openFiles.value.some(f => f.modified)
})

// Methods
const setActiveFile = (fileId: string) => {
  activeFileId.value = fileId
}

const closeFile = (fileId: string) => {
  const index = openFiles.value.findIndex(f => f.id === fileId)
  if (index === -1) return
  
  // If closing active file, switch to another file
  if (fileId === activeFileId.value) {
    if (openFiles.value.length > 1) {
      const newIndex = index === 0 ? 1 : index - 1
      activeFileId.value = openFiles.value[newIndex].id
    } else {
      activeFileId.value = null
    }
  }
  
  openFiles.value.splice(index, 1)
}

const openNewFile = () => {
  const fileId = `file_${Date.now()}`
  const newFile: FileTab = {
    id: fileId,
    name: 'untitled.js',
    content: '',
    language: 'javascript',
    modified: false
  }
  
  openFiles.value.push(newFile)
  activeFileId.value = fileId
}

const openFileDialog = async () => {
  try {
    // Use Electron's dialog to open file
    const result = await window.api.openFileDialog()
    if (result.success && result.filePath) {
      const content = await window.api.readFile(result.filePath)
      const fileName = result.filePath.split('/').pop() || 'unknown'
      
      const fileId = `file_${Date.now()}`
      const newFile: FileTab = {
        id: fileId,
        name: fileName,
        content: content,
        path: result.filePath,
        language: getLanguageFromExtension(fileName),
        modified: false
      }
      
      openFiles.value.push(newFile)
      activeFileId.value = fileId
    }
  } catch (error) {
    console.error('Failed to open file:', error)
    addTerminalLine('error', `Failed to open file: ${error}`)
  }
}

const saveCurrentFile = async () => {
  if (!activeFile.value) return
  
  try {
    if (activeFile.value.path) {
      // Save existing file
      await window.api.writeFile(activeFile.value.path, activeFile.value.content)
      activeFile.value.modified = false
      addTerminalLine('output', `Saved: ${activeFile.value.name}`)
    } else {
      // Save as new file
      const result = await window.api.saveFileDialog(activeFile.value.name, activeFile.value.content)
      if (result.success && result.filePath) {
        activeFile.value.path = result.filePath
        activeFile.value.name = result.filePath.split('/').pop() || activeFile.value.name
        activeFile.value.modified = false
        addTerminalLine('output', `Saved: ${activeFile.value.name}`)
      }
    }
  } catch (error) {
    console.error('Failed to save file:', error)
    addTerminalLine('error', `Failed to save file: ${error}`)
  }
}

const handleFileChange = () => {
  if (activeFile.value) {
    activeFile.value.modified = true
  }
}

const getFileIcon = (fileName: string): string => {
  const ext = fileName.split('.').pop()?.toLowerCase()
  const icons: Record<string, string> = {
    'js': '📄',
    'ts': '📘',
    'vue': '💚',
    'html': '🌐',
    'css': '🎨',
    'json': '📋',
    'md': '📝',
    'py': '🐍',
    'txt': '📄'
  }
  return icons[ext || ''] || '📄'
}

const getLanguageFromExtension = (fileName: string): string => {
  const ext = fileName.split('.').pop()?.toLowerCase()
  const languages: Record<string, string> = {
    'js': 'javascript',
    'ts': 'typescript',
    'vue': 'vue',
    'html': 'html',
    'css': 'css',
    'json': 'json',
    'md': 'markdown',
    'py': 'python'
  }
  return languages[ext || ''] || 'text'
}

const getEditorPlaceholder = (): string => {
  if (!activeFile.value) return ''
  
  const placeholders: Record<string, string> = {
    'javascript': '// Start coding in JavaScript...',
    'typescript': '// Start coding in TypeScript...',
    'vue': '<template>\n  <!-- Your Vue component -->\n</template>',
    'html': '<!DOCTYPE html>\n<html>\n  <!-- Your HTML content -->\n</html>',
    'css': '/* Your CSS styles */',
    'python': '# Start coding in Python...',
    'json': '{\n  // Your JSON data\n}'
  }
  
  return placeholders[activeFile.value.language || ''] || '// Start coding...'
}

// Terminal Methods
const toggleTerminal = () => {
  terminalVisible.value = !terminalVisible.value
  if (terminalVisible.value) {
    nextTick(() => {
      terminalInput.value?.focus()
    })
  }
}

const clearTerminal = () => {
  terminalHistory.value = [
    { type: 'output', text: 'PelicanOS Developer Terminal' },
    { type: 'output', text: 'Type "help" for available commands' }
  ]
}

const addTerminalLine = (type: TerminalLine['type'], text: string) => {
  terminalHistory.value.push({ type, text, timestamp: new Date() })
  nextTick(() => {
    if (terminalContent.value) {
      terminalContent.value.scrollTop = terminalContent.value.scrollHeight
    }
  })
}

const handleTerminalInput = async (event: KeyboardEvent) => {
  if (event.key === 'Enter') {
    const command = currentCommand.value.trim()
    if (!command) return
    
    // Add command to history
    addTerminalLine('command', command)
    currentCommand.value = ''
    
    // Process command
    await executeCommand(command)
  }
}

const executeCommand = async (command: string) => {
  const [cmd, ...args] = command.split(' ')
  
  try {
    switch (cmd.toLowerCase()) {
      case 'help':
        addTerminalLine('output', 'Available commands:')
        addTerminalLine('output', '  help - Show this help')
        addTerminalLine('output', '  clear - Clear terminal')
        addTerminalLine('output', '  ls - List files')
        addTerminalLine('output', '  pwd - Print working directory')
        addTerminalLine('output', '  echo <text> - Echo text')
        break
        
      case 'clear':
        clearTerminal()
        break
        
      case 'ls':
        openFiles.value.forEach(file => {
          addTerminalLine('output', `  ${file.name}${file.modified ? ' *' : ''}`)
        })
        break
        
      case 'pwd':
        addTerminalLine('output', '/developer/workspace')
        break
        
      case 'echo':
        addTerminalLine('output', args.join(' '))
        break
        
      default:
        // Try to execute as system command via IPC
        try {
          const result = await window.api.executeCommand(command)
          if (result.stdout) {
            addTerminalLine('output', result.stdout)
          }
          if (result.stderr) {
            addTerminalLine('error', result.stderr)
          }
        } catch (error) {
          addTerminalLine('error', `Command not found: ${cmd}`)
        }
        break
    }
  } catch (error) {
    addTerminalLine('error', `Error executing command: ${error}`)
  }
}

const shareProject = () => {
  // Implementation for sharing/exporting project
  addTerminalLine('output', 'Share functionality coming soon...')
}

// Lifecycle
onMounted(() => {
  // Create a default file to start with
  openNewFile()
})
</script>

<style scoped>
.developer-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
  border-left: 1px solid rgba(255, 255, 255, 0.1);
  color: white;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

/* Header */
.panel-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background: rgba(0, 0, 0, 0.3);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
}

.developer-badge {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: rgba(34, 197, 94, 0.2);
  padding: 0.5rem 1rem;
  border-radius: 20px;
  border: 1px solid rgba(34, 197, 94, 0.3);
}

.badge-icon {
  font-size: 0.9rem;
}

.badge-text {
  font-size: 0.9rem;
  font-weight: 600;
}

.header-actions {
  display: flex;
  gap: 0.5rem;
}

.header-btn {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 8px;
  color: white;
  cursor: pointer;
  transition: all 0.3s;
  font-size: 0.9rem;
}

.header-btn:hover {
  background: rgba(255, 255, 255, 0.2);
  transform: translateY(-1px);
}

.header-btn.active {
  background: rgba(59, 130, 246, 0.3);
  border: 1px solid rgba(59, 130, 246, 0.5);
}

.close-btn {
  padding: 0.5rem;
}

.close-btn:hover {
  background: rgba(239, 68, 68, 0.3);
}

/* File Navigation */
.file-nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.5rem 1rem;
  background: rgba(0, 0, 0, 0.2);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  min-height: 3rem;
}

.nav-tabs {
  display: flex;
  gap: 0.25rem;
  flex: 1;
  overflow-x: auto;
}

.file-tab {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 6px;
  color: white;
  cursor: pointer;
  transition: all 0.3s;
  white-space: nowrap;
  font-size: 0.85rem;
}

.file-tab:hover {
  background: rgba(255, 255, 255, 0.15);
}

.file-tab.active {
  background: rgba(59, 130, 246, 0.3);
  border: 1px solid rgba(59, 130, 246, 0.5);
}

.file-tab.new-file {
  background: rgba(34, 197, 94, 0.2);
  border: 1px solid rgba(34, 197, 94, 0.3);
}

.file-icon {
  font-size: 0.9rem;
}

.file-name {
  font-size: 0.85rem;
}

.close-file {
  background: none;
  border: none;
  color: rgba(255, 255, 255, 0.6);
  cursor: pointer;
  padding: 0;
  margin-left: 0.5rem;
  font-size: 1rem;
  line-height: 1;
}

.close-file:hover {
  color: white;
}

.nav-actions {
  display: flex;
  gap: 0.5rem;
}

.nav-btn {
  padding: 0.5rem;
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 6px;
  color: white;
  cursor: pointer;
  transition: all 0.3s;
}

.nav-btn:hover:not(:disabled) {
  background: rgba(255, 255, 255, 0.2);
}

.nav-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Editor Container */
.editor-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.editor-container.with-terminal {
  max-height: 60%;
}

.editor-wrapper {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

/* Code Editor */
.code-editor {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
}

.editor-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem 1rem;
  background: rgba(0, 0, 0, 0.2);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.file-path {
  font-size: 0.85rem;
  color: rgba(255, 255, 255, 0.8);
}

.modified-indicator {
  color: #fbbf24;
  font-size: 1.2rem;
  line-height: 1;
}

.code-textarea {
  flex: 1;
  padding: 1rem;
  background: rgba(0, 0, 0, 0.3);
  border: none;
  color: white;
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 0.9rem;
  line-height: 1.5;
  resize: none;
  outline: none;
  white-space: pre;
  overflow-wrap: normal;
  overflow-x: auto;
}

.code-textarea::placeholder {
  color: rgba(255, 255, 255, 0.4);
}

/* Editor Placeholder */
.editor-placeholder {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0.1);
}

.placeholder-content {
  text-align: center;
  color: rgba(255, 255, 255, 0.6);
}

.placeholder-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.placeholder-content h3 {
  font-size: 1.2rem;
  margin-bottom: 0.5rem;
  color: white;
}

.placeholder-content p {
  margin-bottom: 1.5rem;
  font-size: 0.9rem;
}

.create-file-btn {
  padding: 0.75rem 1.5rem;
  background: rgba(59, 130, 246, 0.3);
  border: 1px solid rgba(59, 130, 246, 0.5);
  border-radius: 8px;
  color: white;
  cursor: pointer;
  transition: all 0.3s;
}

.create-file-btn:hover {
  background: rgba(59, 130, 246, 0.4);
  transform: translateY(-1px);
}

/* Terminal */
.terminal-drawer {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 200px;
  max-height: 40%;
  background: rgba(0, 0, 0, 0.4);
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.terminal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.75rem 1rem;
  background: rgba(0, 0, 0, 0.3);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.terminal-title {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.9rem;
  font-weight: 600;
}

.terminal-actions {
  display: flex;
  gap: 0.5rem;
}

.terminal-btn {
  padding: 0.25rem 0.75rem;
  background: rgba(255, 255, 255, 0.1);
  border: none;
  border-radius: 4px;
  color: white;
  cursor: pointer;
  transition: all 0.3s;
  font-size: 0.8rem;
}

.terminal-btn:hover {
  background: rgba(255, 255, 255, 0.2);
}

.terminal-content {
  flex: 1;
  padding: 1rem;
  overflow-y: auto;
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 0.85rem;
  line-height: 1.4;
}

.terminal-line {
  display: flex;
  margin-bottom: 0.25rem;
}

.terminal-line.command {
  color: #22c55e;
}

.terminal-line.error {
  color: #ef4444;
}

.terminal-line.output {
  color: rgba(255, 255, 255, 0.9);
}

.terminal-prompt {
  color: #22c55e;
  margin-right: 0.5rem;
  font-weight: bold;
}

.terminal-input {
  display: flex;
  align-items: center;
  padding: 0.75rem 1rem;
  background: rgba(0, 0, 0, 0.2);
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.command-input {
  flex: 1;
  background: none;
  border: none;
  color: white;
  font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
  font-size: 0.85rem;
  outline: none;
  margin-left: 0.5rem;
}

.command-input::placeholder {
  color: rgba(255, 255, 255, 0.4);
}

/* Scrollbars */
.nav-tabs::-webkit-scrollbar,
.terminal-content::-webkit-scrollbar {
  height: 4px;
  width: 4px;
}

.nav-tabs::-webkit-scrollbar-track,
.terminal-content::-webkit-scrollbar-track {
  background: rgba(255, 255, 255, 0.1);
}

.nav-tabs::-webkit-scrollbar-thumb,
.terminal-content::-webkit-scrollbar-thumb {
  background: rgba(255, 255, 255, 0.3);
  border-radius: 2px;
}

.nav-tabs::-webkit-scrollbar-thumb:hover,
.terminal-content::-webkit-scrollbar-thumb:hover {
  background: rgba(255, 255, 255, 0.5);
}
</style>
